FROM python:3.9.7
WORKDIR .
ADD requirements.txt .
RUN pip3 install -r requirements.txt
ADD . .

ENV FLASK_APP=app
ENV FLASK_ENV=production
ENV SECRET_KEY=funnykey

EXPOSE 3000

CMD ["flask", "run", "--host=0.0.0.0", "--port", "3000"]