FROM python:3.9.7
WORKDIR /app
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY . .

ENV ASYNC_MODE=eventlet

EXPOSE 3000

CMD ["gunicorn", "--worker-class", "eventlet", "-w", "1", "-b", "0.0.0.0:3000", "app:app"]